// js/ztf_game_data.js

const initialLanguageChoices = [
    { id: 'es', name: 'Spanish', flagIcon: 'https://flagcdn.com/w40/es.png', family: 'romance', difficulty: 1, resources: 5, startExplainer: "Spanish: A widely spoken Romance language with rich culture and relatively accessible grammar for English speakers. A great first ascent!" },
    { id: 'fr', name: 'French',  flagIcon: 'https://flagcdn.com/w40/fr.png', family: 'romance', difficulty: 2, resources: 5, startExplainer: "French: The language of diplomacy and art. Its sounds can be tricky but its global presence offers vast resources. Bon voyage!" },
    { id: 'de', name: 'German', flagIcon: 'https://flagcdn.com/w40/de.png', family: 'germanic', difficulty: 3, resources: 4, startExplainer: "German: A language of precision and depth. Its grammar is structured, offering a unique challenge and reward. Viel Erfolg!" },
    { id: 'id', name: 'Indonesian', flagIcon: 'https://flagcdn.com/w40/id.png', family: 'austronesian', difficulty: 1, resources: 3, startExplainer: "Indonesian (Bahasa Indonesia): Known for its relatively simple grammar, making it an accessible entry into a new language family. Selamat belajar!" },
    { id: 'it', name: 'Italian', flagIcon: 'https://flagcdn.com/w40/it.png', family: 'romance', difficulty: 2, resources: 4, startExplainer: "Italian: The language of art, music, and cuisine. Similar to other Romance languages, with beautiful phonetics. In bocca al lupo!" },
    { id: 'pt', name: 'Portuguese', flagIcon: 'https://flagcdn.com/w40/pt.png', family: 'romance', difficulty: 2, resources: 4, startExplainer: "Portuguese: Spoken across continents, from Brazil to Portugal. Shares many similarities with Spanish. Boa sorte!" },
    { id: 'ru', name: 'Russian', flagIcon: 'https://flagcdn.com/w40/ru.png', family: 'slavic', difficulty: 4, resources: 3, startExplainer: "Russian: A rich Slavic language with a different script and complex grammar. Unlocks a vast world of literature and culture. Удачи!" },
    { id: 'sv', name: 'Swedish', flagIcon: 'https://flagcdn.com/w40/se.png', family: 'germanic', difficulty: 2, resources: 3, startExplainer: "Swedish: A North Germanic language known for its melodic tone. A good entry point into Scandinavian languages. Lycka till!" },
];

const cefrLevels = {
    'a1': { name: "A1 - Explorer", luThreshold: 0, characterArt: "../assets/A2_art_bg_with_character.png", levelUpExplainerTitle: "A1 Explorer: The First Steps!", levelUpExplainerText: "You've begun your linguistic adventure! At A1, focus on absorbing the very basics: common words, simple phrases, and the fundamental sounds. Aljohn says: 'Assume you know nothing. Anki and Language Transfer are your best friends here to build that initial frame.'" },
    'a2': { name: "A2 - Novice", luThreshold: 150000, characterArt: "../assets/A2_art_bg_with_character.png", levelUpExplainerTitle: "A2 Novice: Foundation Laid!", levelUpExplainerText: "Solid work! You understand simple sentences and can grasp the gist of basic texts. Aljohn's Tip: 'You now have ~1000 words in Anki (roughly 100,000 LU). It's time to start seeing them in context. Unlock Simple Texts and begin reading familiar stories!'" },
    'b1': { name: "B1 - Adept Apprentice", luThreshold: 750000, characterArt: "../assets/B2_art_bg_with_character.png", levelUpExplainerTitle: "B1 Adept Apprentice: The Immersion Gateway!", levelUpExplainerText: "A major leap! Your vocabulary and grammar base are solidifying. You can understand much more. Aljohn emphasizes: 'Now, the goal is to FEEL the language. Shift your Deliberate Practice to MASSIVE INPUT with native content. Unlock Native Watching and Listening methods. Use target language subtitles ONLY. This is where subconscious acquisition truly begins!'" },
    'b2': { name: "B2 - Fluent Adept", luThreshold: 3000000, characterArt: "../assets/B2_art_bg_with_character.png", levelUpExplainerTitle: "B2 Fluent Adept: Comprehension Unlocked!", levelUpExplainerText: "Incredible! You understand most native content without subtitles and can navigate complex discussions on familiar topics. Aljohn notes: 'At B2, with 2500+ Anki words (representing millions of LU) and hundreds of immersion hours, conversations flow more naturally. Start gentle output like journaling and AI chat practice.'" },
    'c1': { name: "C1 - Skilled Master", luThreshold: 12000000, characterArt: "../assets/C2_art_bg_with_character.png", levelUpExplainerTitle: "C1 Skilled Master: Polishing the Craft!", levelUpExplainerText: "You're highly proficient and can express yourself with nuance! Aljohn says: 'Now, your Deliberate Practice focuses on subtle details: tone, register, complex idioms, and cultural understanding. Intensive Native Interaction and Shadowing are key to sounding truly natural and refining your advanced skills.'" },
    'c2': { name: "C2 - Grand Master", luThreshold: 35000000, characterArt: "../assets/C2_art_bg_with_character.png", levelUpExplainerTitle: "C2 Grand Master: Language Owned!", levelUpExplainerText: "Вы достиг Мастерства! (You have achieved Mastery!) You think, feel, and create in the language. Aljohn's wisdom: 'The journey of deepening understanding never truly ends, but you've achieved a remarkable milestone. You can now choose to Ascend to a new language, carrying forth the wisdom gained!'" }
};

const upgradesData = [
    // A1-A2 Methods
    { id: 'ankiA1', name: 'Anki Deck (A1-A2)', cost: 20, baseLps: 0.2, clickLuFlatBonus: 0.2, icon: '../assets/A2_anki_gem_icon.png', description: 'Spaced Repetition for foundational vocabulary.', explainerTitle: "Insight: The Power of Anki", explainerText: "Aljohn considers Anki NON-NEGOTIABLE. It uses Spaced Repetition (SRS) to drill words into your long-term memory scientifically. Start your deck on Day 1, adding words AND example sentences from your input. Aim for 1000 reviewed items (representing ~100k LU) to solidify A2.", unlockLevel: 'a1' },
    { id: 'langTransferA1', name: 'Language Transfer Course', cost: 100, baseLps: 0, oneTimeLuBoost: 1000, clickLuFlatBonus: 0.1,icon: '../assets/A2_character_langauge_transfer.png', description: 'Understand the language\'s core logic quickly.', explainerTitle: "Insight: Language Transfer's Logic", explainerText: "This audio course reveals the 'skeleton' of the language, often showing connections to English. Aljohn completes it in a few days to grasp the foundational grammar and unlock an initial burst of comprehension.", unlockLevel: 'a1', maxOwn: 1 },
    { id: 'duolingoA1', name: 'Duolingo Spark (A1)', cost: 10, baseLps: 0.1, icon: 'https://cdn.iconscout.com/icon/free/png-256/free-duolingo-icon-download-in-svg-png-gif-file-formats--symbol-brand-logo-world-logos-vol-2-pack-icons-282167.png?f=webp', description: 'Initial familiarization with sounds & structure.', explainerTitle: "Insight: Duolingo's Initial Role", explainerText: "Aljohn uses Duolingo only briefly at the very start (the first few lessons) to get a feel for the language's sounds and basic sentence structure. It helps build initial momentum, but don't get bogged down; move on quickly to more intensive methods!", unlockLevel: 'a1', maxOwn: 10 },
    { id: 'simpleTextsA1', name: 'Simple Texts Reader (A1-A2)', cost: 300, baseLps: 1.0, baseClickLuMultiplierBonus: 0.1, icon: '../assets/A2_basic_text_icon.png', description: 'Read familiar stories and simple articles with tap-to-translate.', explainerTitle: "Insight: Reading Simple Texts", explainerText: "Once you have a few hundred words (around 30-50k LU from Anki), reading familiar stories (like Harry Potter) or simple online articles provides vital comprehensible input. You know the plot, so you focus on the language. Tools like ReadEra with tap-to-translate are invaluable here.", prerequisites: { upgrades: { ankiA1: 1 }, luWords: 30000 }, unlockLevel: 'a1' },
    { id: 'youtubeGrammarA1', name: 'Basic Grammar Videos (A1-A2)', cost: 200, baseLps: 0.5, clickLuFlatBonus: 1, icon: '../assets/B2_youtube_crystal_icon.png', description: 'Watch short grammar explainers on YouTube for core concepts.', explainerTitle: "Insight: Foundational Grammar via Video", explainerText: "Aljohn uses YouTube for clear, concise explanations of basic grammar or consults beginner textbooks. The goal isn't rote memorization yet, but building an intuitive feel for how the language works. Use ChatGPT to clarify confusing points!", unlockLevel: 'a1' },
    // B1-B2 Methods
    { id: 'ankiB1', name: 'Anki Expansion (B1-B2)', cost: 1500, baseLps: 3, icon: '../assets/A2_anki_gem_icon.png', description: 'Expand vocabulary with native sentences from your immersion activities.', explainerTitle: "Insight: Anki for B1-B2 - Sentence Mining", explainerText: "Continue Anki relentlessly! Now, your focus shifts to 'sentence mining' – adding full, interesting sentences and nuanced vocabulary encountered during your massive input. This builds deeper contextual understanding. Aim for 2500+ reviewed items (representing millions of LU) for a solid B2.", prerequisites: { cefrLevel: 'b1', upgrades: { ankiA1: 5 } }, unlockLevel: 'b1' },
    { id: 'nativeReadingB1', name: 'Native Reading Immersion', cost: 1000, baseLps: 8, icon: '../assets/B2_books_icon.png', description: 'Dive into novels, news, and blogs that you genuinely enjoy.', explainerTitle: "Insight: Immersive Native Reading", explainerText: "At B1, it's time to shift to authentic native materials! Reading what interests *you* makes immersion sustainable and enjoyable. Aljohn emphasizes: 'This is where your vocabulary acquisition explodes, and you start to truly feel the language.'", prerequisites: { cefrLevel: 'b1', upgrades: { simpleTextsA1: 3 } }, unlockLevel: 'b1' },
    { id: 'nativeWatchingB1', name: 'Native Video Immersion', cost: 1800, baseLps: 12, icon: '../assets/C2_advanced_content_tv_icon.png', description: 'YouTube, streaming platforms with TARGET LANG subtitles ONLY.', explainerTitle: "Insight: Native Audiovisual Input (B1-B2)", explainerText: "Immerse yourself in native YouTube channels, TV shows, and movies (use a VPN if needed!). Aljohn's crucial rule: 'Target language subtitles ONLY, to directly link sound with text and build natural comprehension.' Language Reactor extension can help here.", prerequisites: { cefrLevel: 'b1' }, unlockLevel: 'b1' },
    { id: 'nativeListeningB1', name: 'Native Audio Immersion', cost: 900, baseLps: 6, icon: '../assets/B2_podcasts_icon.png', description: 'Podcasts, audiobooks, radio, music during all "dead time".', explainerTitle: "Insight: Filling Dead Time with Audio", explainerText: "Turn commuting, chores, and workouts into valuable listening immersion. Aljohn uses Pocket Casts for offline podcasts. He stresses: 'Music is especially powerful for internalizing pronunciation, rhythm, and common slang!'", prerequisites: { cefrLevel: 'b1' }, unlockLevel: 'b1' },
    { id: 'musicImmersionB1', name: 'Music Immersion Focus', cost: 700, baseLps: 5, icon: '../assets/B2_Musicians_character.png', description: 'Actively listen to and learn lyrics from music in your target language.', explainerTitle: "Insight: The Power of Music", explainerText: "Songs are fantastic for learning! Aljohn finds they help internalize pronunciation, rhythm, slang, and common phrases in a memorable way. Find artists you like and dive into their lyrics.", prerequisites: { cefrLevel: 'b1' }, unlockLevel: 'b1' },
    { id: 'journalingB1', name: 'Daily Journaling (B1-B2)', cost: 1200, baseLps: 0, clickLuBoost: 10000, cooldown: 18000, icon: '../assets/B2_journal_icon.png', description: 'Gentle output: Write daily to activate vocabulary and grammar. Click for LU boost.', explainerTitle: "Insight: Gentle Output - Journaling", explainerText: "Start expressing yourself in writing! Aljohn journals daily about his day, opinions, or summaries of content. 'Use DeepL or ChatGPT initially for tricky phrasing, but the main goal is to get your thoughts out and identify vocabulary gaps.'", prerequisites: { cefrLevel: 'b1' }, unlockLevel: 'b1' }, // Cooldown in seconds (5 hours)
    { id: 'deeplAssistB1', name: 'DeepL Translator Assist', cost: 400, baseLps: 0, icon: '../assets/B2_DeepL_floating_fairy_character.png', description: 'High-quality translation aid for complex phrases or checking understanding.', explainerTitle: "Insight: DeepL for Precision", explainerText: "When writing or trying to understand complex sentences, Aljohn uses DeepL for its accuracy. 'It's great for checking if your phrasing is natural or understanding nuanced text. Use it as a helper, not a crutch for full translation.'", prerequisites: { cefrLevel: 'b1' }, unlockLevel: 'b1', maxOwn: 5 },
    { id: 'chatGPTAssistB1', name: 'ChatGPT Assistant (B1-B2)', cost: 3000, baseLps: 0, globalLpsMultiplierBonus: 0.1, icon: '../assets/B2_ChatGPT_Companion_character.png', description: 'Feedback, corrections, conversation simulation. Boosts all LPS by 10%.', isGlobalMultiplier: true, prerequisites: { cefrLevel: 'b1' }, unlockLevel: 'b1' },
    { id: 'immersionTrackerB1', name: 'Immersion Hour Logging', cost: 800, baseLps: 0, globalLpsMultiplierBonus: 0.05, icon: '../assets/B2_immersion_tracker_icon.png', description: 'Track active hours for +5% global LPS. Essential for accountability!', explainerTitle: "Insight: The Power of Tracking Hours", explainerText: "Aljohn stresses: 'Fluency is about HOURS of quality contact, not days or months. Track your reading, watching, listening. It keeps you accountable and shows your true progress.' This unlocks a permanent boost to all learning.", isGlobalMultiplier: true, maxOwn: 1, prerequisites: { cefrLevel: 'b1' }, unlockLevel: 'b1' },
    // C1-C2 Methods
    { id: 'nativeInteractionC1', name: 'Intensive Native Interaction', cost: 20000, baseLps: 60, icon: '../assets/C2_scholars_character.png', description: 'Deep, regular conversations with native speakers and qualified tutors.', explainerTitle: "Insight: True Native Interaction", explainerText: "Time for the real deal! Aljohn advises: 'Converse regularly and deeply. Use iTalki for targeted tutor feedback to identify subtle flaws. Join Discord/Tandem for diverse exchanges. Push yourself into complex discussions on varied topics.'", prerequisites: { cefrLevel: 'c1' }, unlockLevel: 'c1' },
    { id: 'shadowingC1', name: 'Shadowing & Mimicking', cost: 15000, baseLps: 0, activeClickMultiplier: 2, cooldown: 3600, icon: '../assets/C2_shadowing_ghost_character.png', description: 'Mimic native speaker accent, rhythm, intonation. Boosts active study clicks by 2x for 1hr.', explainerTitle: "Insight: The Art of Shadowing", explainerText: "Aljohn picks 'accent models' (native speakers whose speech he admires) and mimics them intensely. 'This is hard work but incredibly effective for sounding natural, improving flow, and boosting confidence.' This method enhances your active learning clicks.", prerequisites: { cefrLevel: 'c1' }, unlockLevel: 'c1' }, // Cooldown for the buff in seconds (1 hour)
    { id: 'advancedContentC1', name: 'Advanced Content Mastery', cost: 30000, baseLps: 100, icon: '../assets/C2_advanced_content_tv_icon.png', description: 'Consume debates, academic lectures, complex literature, dialect-heavy content.', explainerTitle: "Insight: Consuming Advanced & Niche Content", explainerText: "Continuously challenge your comprehension! Aljohn watches political debates, academic lectures, and reads complex literature. 'Push your understanding to its absolute limits with material slightly beyond your comfort zone.'", prerequisites: { cefrLevel: 'c1' }, unlockLevel: 'c1' },
    { id: 'refiningOutputC1', name: 'Refined Output Practice', cost: 25000, baseLps: 0, clickLuBoost: 100000, cooldown: 36000, icon: '../assets/C2_advanced_text_icon.png', description: 'Complex journaling, essays, abstract topics with detailed feedback. Click for large LU boost.', explainerTitle: "Insight: Mastering Complex Expression", explainerText: "Move beyond everyday topics to express sophisticated ideas with precision. Aljohn practices writing complex essays and speaking on abstract themes. 'Get detailed feedback from advanced speakers or tutors on your style and tone.'", prerequisites: { cefrLevel: 'c1' }, unlockLevel: 'c1' }, // Cooldown in seconds (10 hours)
    { id: 'chatGPTMasteryC1', name: 'ChatGPT Mastery (C1-C2)', cost: 60000, baseLps: 0, globalLpsMultiplierBonus: 0.20, icon: '../assets/C2_ChatGPT_floating_fairy_character.png', description: 'Refine complex ideas, explore nuanced expression, advanced roleplay. Boosts all LPS by 20%.', isGlobalMultiplier: true, prerequisites: { cefrLevel: 'c1', upgrades: { chatGPTAssistB1: 1} }, unlockLevel: 'c1' },
    { id: 'culturalNuanceC1', name: 'Cultural Nuance Integration', cost: 80000, baseLps: 40, icon: '../assets/C2_cultural_understanding_icon.png', description: 'Deepen understanding of cultural context, subtext, humor, and register.', explainerTitle: "Insight: Living and Breathing the Culture", explainerText: "True mastery includes profound cultural understanding. Aljohn emphasizes: 'Understand humor, historical references, current events, and appropriate register for diverse social situations. This comes from deep, ongoing immersion in the culture itself, not just the language.'", prerequisites: { cefrLevel: 'c1' }, unlockLevel: 'c1' }
];

const generalExplainers = {
    welcome: { title: "The Path Begins: Choose Your Ascent!", text: "Welcome, Aspirant, to 'From Zero to Fluency'! This journey mirrors Aljohn Polyglot's intensive methods. Your first step: select a language to master. Remember Aljohn's advice: choose a language that genuinely excites you or one with abundant resources. This initial passion or accessibility will fuel your early progress. Click a flag to begin!", icon: "../assets/meeting_wise_wizard.png" },
    deliberatePracticeIntro: { title: "The Key: Deliberate Practice", text: "Aljohn stresses that rapid fluency isn't magic, it's about *Deliberate Practice*. This means focused, systematic effort to improve specific skills. As James Clear says, it's 'purposeful and systematic,' not mindless repetition. Your accumulation of Lexical Units (LU) represents this focused effort. Each Learning Method you unlock is a tool for more effective Deliberate Practice.", icon: "../assets/B2_immersion_tracker_icon.png" },
    firstMethodUnlocked: { title: "Your First Tool Forged!", text: "You've unlocked your first Learning Method! Each method in Aljohn's toolkit contributes to your overall immersion and understanding by facilitating Deliberate Practice. Keep acquiring LU to unlock more powerful techniques and accelerate your journey up the CEFR levels.", icon: "../assets/banner_starter_gear.png" },
    intuitionThresholdReached: { title: "Insight: The Shift to Intuition!", text: "Through consistent, deliberate exposure (represented by your high LU generation from input methods), comprehension is becoming more automatic! Aljohn notes this is when you start to *think* and *feel* the language directly. Your passive LU generation from immersion methods will now be significantly boosted! Keep feeding the engine with diverse input!", icon: "../assets/C2_shadowing_ghost_character.png" },
    languageMastered: { title: "Grand Master of [LanguageName]!", text: "Congratulations! You've reached the pinnacle of [LanguageName] fluency, C2 Grand Master! You 'own' this language. Your dedication to Deliberate Practice has paid off. Aljohn says: 'The journey of deepening understanding never truly ends, but you've achieved a remarkable milestone. Now, will you embark on a new linguistic ascent?' Each mastered language will make the next one feel a little easier, especially those from the same language family.", icon: "../assets/c2_citadel_banner.png" },
    effortRequired: { title: "A Word from Aljohn: Effort & Time", text: "Remember, true fluency, like Aljohn achieved, requires hundreds, even thousands, of focused hours. This game reflects that. Keep accumulating LU through consistent 'study' and by strategically investing in Learning Methods. There are no shortcuts to the C2 Citadel!", icon: "../assets/warning.png" }
};