// D:\website\apps\js\apps_data.js

const allAppData = [
    {
        id: "app-anki",
        name: "Anki / AnkiDroid",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Anki-icon.svg/2048px-Anki-icon.svg.png",
        tagline: "The Flashcard app to never forget what you learned.",
        myTake: "Do you always forget what you've studied? It's probably because you're not using this app. Anki is a flashcard app, and everything you learn should be put here so you never forget it. It's not just a normal flashcard app; it follows an algorithm called \"spaced repetition,\" which is scientifically proven. It helps solidify our learnings from short-term to long-term memory. Based on my experience, it's very effective. This is the #1 app I can't live without. It's the cornerstone for vocabulary and concept memorization across all my languages. You should be making your own cards from day one, adding words and example sentences from your reading and listening.",
        rating: 10,
        pros: ["User-friendly interface for efficient study sessions.", "Proven spaced repetition system (SRS) for optimal learning.", "Cross-platform compatibility (Desktop, Android).", "Highly customizable card types and decks.", "Active community and vast library of shared decks."],
        cons: ["Steep learning curve for advanced customization.", "iOS version (AnkiMobile) is a paid app.", "Requires discipline to keep up with daily reviews consistently."],
        websiteUrl: "https://apps.ankiweb.net/",
        androidUrl: "https://play.google.com/store/apps/details?id=com.ichi2.anki",
        iosUrl: "https://apps.apple.com/us/app/ankimobile-flashcards/id373493387",
        windowsUrl: "https://apps.ankiweb.net/",
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "High", A2: "High", B1: "Medium", B2: "Low", C1: "Low", C2: "Low" },
        immersionTypes: ["Vocabulary Building", "Reading", "Writing", ],
        primaryCategories: ["SRS", "Vocabulary Building"],
        skillFocus: ["Vocabulary Retention", "Concept Memorization", "Active Recall", "Grammar Pattern Recognition"],
        cost: "Free",
        platforms: ["Web", "Android", "iOS", "Windows"],
        tags: ["flashcards", "spaced repetition", "srs", "vocabulary", "memorization", "core utility", "active recall", "must-have"]
    },
    {
        id: "app-chatgpt",
        name: "ChatGPT",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/1024px-ChatGPT_logo.svg.png",
        tagline: "Your versatile AI language-learning partner & tutor.",
        myTake: "If I could give more than 10 stars, this would be it. It's indispensable. For beginners, it can generate reading materials. For intermediate learners, it's a speaking partner. For advanced users, it can pose complex 'Miss Universe-style' questions to hone command of the language. I use its voice feature daily; it's like having a personal tutor on call, which skyrocketed my progress because I no longer 'needed' to talk to real people for initial practice. It's also crucial for my writing practice – when I can't figure out how to say something for my daily diary, I ask ChatGPT for phrasing ideas or to check my grammar. It helps bridge the gap between passive knowledge and active production, generating prompts, rephrasing sentences, or explaining complex grammar. It's one of my 'two wives' in language learning for active engagement and refinement.",
        rating: 10,
        pros: ["Real-time feedback and corrections on language usage.", "Endless conversation practice with an adaptable AI partner.", "Access to information and explanations on demand.", "Role-playing and simulated real-world scenarios.", "Excellent voice feature for conversation practice.", "Supports a vast number of languages.", "Great for translating colloquial/informal language.", "Helps formulate thoughts and sentences for writing.", "Generates writing prompts and examples."],
        cons: ["May provide incorrect or misleading information, especially for less common languages; always verify critical info.", "Misinterpreting prompts can lead to confusing or irrelevant responses.", "Voice feature may not fully capture all nuances of human conversation.", "Might not catch subtle stylistic issues in writing without specific prompting."],
        websiteUrl: "https://chatgpt.com/",
        androidUrl: "https://play.google.com/store/apps/details?id=com.openai.chatgpt",
        iosUrl: "https://apps.apple.com/app/openai-chatgpt/id6448311069",
        windowsUrl: null,
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Low", A2: "Medium", B1: "High", B2: "Medium", C1: "Medium", C2: "Medium" },
        immersionTypes: ["Speaking", "Writing", "Reading", "Listening", "Grammar Focus", "Vocabulary Building"],
        primaryCategories: ["AI Tutor", "Language Exchange", "Writing Checker", "Translation Tool"],
        skillFocus: ["Conversational Practice", "Writing Assistance", "Grammar Explanation", "Pronunciation Practice", "Creative Output"],
        cost: "Free",
        platforms: ["Web", "Android", "iOS"],
        tags: ["ai language learning", "conversation practice", "writing tool", "grammar check", "ai tutor", "speaking partner", "must-have"]
    },
    {
        id: "app-youtube",
        name: "YouTube",
        logoUrl: "https://cdn3.iconfinder.com/data/icons/social-network-30/512/social-06-512.png",
        tagline: "Your free ticket to infinite language immersion.",
        myTake: "This is another app I'd give more than 10 stars. Why complicate finding materials? Everything is here. Beginner? Watch lectures and tutorials. Intermediate/Advanced? Immerse in native content. You can choose videos based on your interests, so you're never bored. Spending time on this platform alone will take you places. Auto-subtitles are great for following along (use target language subs!). Create separate YouTube accounts for each language to train the algorithm effectively. It's the 'All-Encompassing Mother of Authentic Input', one of my 'two wives' that shows me the world in the language.",
        rating: 10,
        pros: ["Virtually endless content for language exposure in almost any language.", "Automatic subtitles (target language preferred) for many videos.", "Extensive language learning tutorials and channels.", "Accessible across all devices.", "Completely free.", "Visual context aids comprehension.", "Algorithm can be trained for personalized content."],
        cons: ["Limited or inaccurate automatic subtitle availability for certain languages or niche content.", "Can be highly distracting with non-language content if not disciplined.", "Quality of learner-focused content varies greatly."],
        websiteUrl: "https://www.youtube.com/",
        androidUrl: "https://play.google.com/store/apps/details?id=com.google.android.youtube",
        iosUrl: "https://apps.apple.com/us/app/youtube-watch-listen-stream/id544007664",
        windowsUrl: null,
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Low", A2: "Medium", B1: "High", B2: "High", C1: "High", C2: "High" },
        immersionTypes: ["Listening", "Watching", "Reading"],
        primaryCategories: ["Content Platform", "Media Player"],
        skillFocus: ["Auditory Comprehension", "Cultural Immersion", "Exposure to Native Speech Patterns", "Vocabulary Acquisition"],
        cost: "Free",
        platforms: ["Web", "Android", "iOS"],
        tags: ["video content", "native content", "immersion", "listening practice", "visual learning", "tutorials", "must-have"]
    },
    {
        id: "app-readera",
        name: "ReadEra",
        logoUrl: "https://play-lh.googleusercontent.com/qw8lAHXaZodAE4c3D1Jkia3V8Np-PxTnyQpUIx439ibABba0L50TVKI4jfY4N4QwzAA",
        tagline: "Your all-in-one offline reading companion.",
        myTake: "Actually, any ebook reader is fine, but this is what I personally use. And if there are words I don't know, it has a built-in translator (I don't know if it only works on Android). You can also highlight phrases or words depending on how you use it. Its interface is easy and intuitive. And if you like audio while reading, it also has a voice feature so you can hear the language while reading it. Perfect for my strategy of reading familiar books (like Harry Potter) in my target language in the beginner stages, and any native content later on.",
        rating: 10,
        pros: ["Intuitive and user-friendly interface for various ebook formats (EPUB, PDF, etc.).", "Built-in dictionary/translator integration (availability may vary).", "Text-to-speech function with multiple language support.", "Convenient highlighting and note-taking features.", "Suitable for readers of all levels, supporting massive input.", "Completely free with no ads (for the basic version)."],
        cons: ["Requires manual downloading and importing of book files.", "Advanced features might be in a premium version for some users."],
        websiteUrl: "https://readera.org/",
        androidUrl: "https://play.google.com/store/apps/details?id=org.readera",
        iosUrl: null,
        windowsUrl: null,
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Medium", A2: "Medium", B1: "High", B2: "High", C1: "High", C2: "High" },
        immersionTypes: ["Reading", "Vocabulary Building"],
        primaryCategories: ["Reading Assistant", "Media Player"],
        skillFocus: ["Reading Comprehension", "Vocabulary Acquisition in Context", "Massive Input"],
        cost: "Free",
        platforms: ["Android"],
        tags: ["ebook reader", "reading practice", "offline reading", "epub", "pdf", "vocabulary"]
    },
    {
        id: "app-pocketcasts",
        name: "Pocket Casts",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Pocket_Casts_icon.svg/2048px-Pocket_Casts_icon.svg.png",
        tagline: "Your go-to app for multilingual podcast immersion.",
        myTake: "This is my personal podcast player. Its competitors are Spotify and YouTube Music, but Spotify needs internet and doesn't allow downloads (for free tier). YouTube Music has a difficult interface. But Pocket Casts is very intuitive to use. It also tracks your listening hours so you have data on how long your immersion has been so far. Almost all podcasts available on other platforms are here too. I discovered this recently since Google Podcasts was discontinued, and I'm glad I found it. You can also play it in the background if you want to do laundry or cook while studying. Essential for my 'dead time' immersion strategy.",
        rating: 10,
        pros: ["Offline listening capabilities are excellent.", "Vast podcast library and discovery features.", "Adjustable playback speed and volume boost.", "Tracks listening statistics (hours listened).", "Background playback for multitasking.", "User-friendly and intuitive interface.", "Cross-platform."],
        cons: ["Can be overwhelming for users new to podcasts due to the sheer volume of content.", "Some advanced features might require the paid 'Plus' version."],
        websiteUrl: "https://pocketcasts.com/",
        androidUrl: "https://play.google.com/store/apps/details?id=au.com.shiftyjelly.pocketcasts",
        iosUrl: "https://apps.apple.com/us/app/pocket-casts/id414834813",
        windowsUrl: "https://play.pocketcasts.com/",
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Very Low", A2: "Medium", B1: "High", B2: "High", C1: "High", C2: "High" },
        immersionTypes: ["Listening"],
        primaryCategories: ["Media Player", "Content Platform"],
        skillFocus: ["Auditory Comprehension", "Exposure to Native Speech", "Passive Immersion", "Cultural Insights"],
        cost: "Free",
        platforms: ["Web", "Android", "iOS"],
        tags: ["podcasts", "audio content", "listening practice", "immersion", "background listening"]
    },
    {
        id: "app-deepl",
        name: "DeepL Translator",
        logoUrl: "https://cdn.worldvectorlogo.com/logos/deepl-1.svg",
        tagline: "Your ultimate companion for accurate translations.",
        myTake: "For me, this is the best translator because it's incredibly accurate, and its translations don't look awkward. The only disadvantage is that it has fewer languages (though they add more with every update), and it needs Wi-Fi because you can't download language files like Google Translate. But overall, this is where I get the sentences I imitate. It's 9 stars because ChatGPT is still different for translating informal language. DeepL is very formal, same as Google Translate. So if you want street language, this isn't perfect. I use it when writing my essays in my target language to check phrasing or find technical jargon.",
        rating: 10,
        pros: ["Exceptional translation accuracy, often sounding more natural than competitors.", "User-friendly interface.", "Provides alternative phrasings for translations.", "Generally free for reasonable use."],
        cons: ["Limited language options compared to Google Translate.", "Doesn't capture nuances in very informal or colloquial language well.", "Requires an internet connection; no offline mode.", "Free version has character limits per translation and volume limits."],
        websiteUrl: "https://www.deepl.com/translator",
        androidUrl: "https://play.google.com/store/apps/details?id=com.deepl.mobiletranslator",
        iosUrl: "https://apps.apple.com/us/app/deepl-translate/id155242908DeepL", // URL seems cut, assuming it's correct from a previous entry
        windowsUrl: "https://www.deepl.com/app/",
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "High", A2: "High", B1: "Medium", B2: "Medium", C1: "Low", C2: "Low" },
        immersionTypes: ["Reading", "Writing", "Vocabulary Building"],
        primaryCategories: ["Translation Tool", "Dictionary"],
        skillFocus: ["Translation Accuracy", "Understanding Complex Sentences", "Vocabulary Lookup"],
        cost: "Free",
        platforms: ["Web", "Android", "iOS", "Windows"],
        tags: ["translator", "accurate translation", "dictionary", "writing aid", "reading aid"]
    },
    {
        id: "app-languagetransfer",
        name: "Language Transfer",
        logoUrl: "https://play-lh.googleusercontent.com/upG4JV3kjl9LDKjhgONsmboRlAnsfJJsuMc_XeUm_q7ft6erVMfIWyunNfoLjMqB93I",
        tagline: "The best free audio courses for understanding language structure.",
        myTake: "This is the perfect app for beginners. It's like having a one-on-one teacher who teaches you the basics of a language. It explains the root of each word and how grammar works. You'll also learn cultural insights about the language you're studying, so it's perfect. If you're a beginner, you can do this while multitasking to save time. The only downside is it covers few languages. But since most of you are learning French or Spanish, this is just right. I completed the Spanish course in just three days and it was incredibly effective.",
        rating: 10,
        pros: ["Offers comprehensive grammar explanations through 'The Thinking Method'.", "Interactive audio exercises guide you to construct sentences.", "Includes cultural insights and etymology.", "Background playback allows for multitasking.", "Completely free and volunteer-driven."],
        cons: ["Limited language options currently available.", "No visual material, purely audio-based.", "Lack of formal progress tracking or user data within the app/platform.", "Course duration for each language can be long, requiring sustained attention."],
        websiteUrl: "https://www.languagetransfer.org/",
        androidUrl: "https://play.google.com/store/apps/details?id=org.languagetransfer",
        iosUrl: "https://apps.apple.com/us/app/language-transfer/id1519509085",
        windowsUrl: null,
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "High", A2: "Very Low", B1: "Very Low", B2: "Very Low", C1: "Very Low", C2: "Very Low" },
        immersionTypes: ["Listening", "Grammar Focus"],
        primaryCategories: ["Course Platform"],
        skillFocus: ["Grammar Comprehension", "Sentence Construction", "Understanding Language Logic"],
        cost: "Free",
        platforms: ["Web", "Android", "iOS"],
        tags: ["audio course", "grammar explanation", "beginner friendly", "language structure", "thinking method"]
    },
    {
        id: "app-urbanvpn",
        name: "UrbanVPN",
        logoUrl: "https://appteka.store/api/1/icon/get?hash=TPZUwy3ibxCBwnP7i2PfRbtKOgAWeRa2813msljIixgwTq0elKPFKyZrnujcxd%2BP",
        tagline: "Your Free Gateway to Geo-Restricted Language Immersion.",
        myTake: "I'm just inserting this app, especially for PC users. I've tried many VPN services, but this is the only one that's truly free for many useful locations. With this VPN, I can access other sites to get more resources. For example, if it's Spanish, you can watch RTVE, which is like Netflix but Spanish. In the Philippines, it's equivalent to iWantTFC or Vivamax. It's not required, but if you're bored with YouTube and want different content or to access content you can't easily find, you need this.",
        rating: 10,
        pros: ["Provides access to geo-restricted content in various target languages.", "Enhances immersion possibilities by unlocking native TV shows, movies, and websites.", "Relatively user-friendly interface.", "Free to use for many server locations."],
        cons: ["Connection speed can fluctuate significantly.", "Effectiveness depends on the availability and quality of content in the target region/server.", "Free VPNs may have privacy concerns for some users; use with awareness.", "May have ads or prompts to upgrade."],
        websiteUrl: "https://www.urban-vpn.com/",
        androidUrl: "https://play.google.com/store/apps/details?id=com.urbanvpn.android",
        iosUrl: "https://apps.apple.com/us/app/urban-vpn-proxy/id1517763110",
        windowsUrl: "https://www.urban-vpn.com/windows-vpn/",
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Low", A2: "Medium", B1: "High", B2: "High", C1: "High", C2: "High" }, // Inferred
        immersionTypes: ["Watching", "Listening", "Reading"],
        primaryCategories: ["Utility"],
        skillFocus: ["Content Access", "Cultural Immersion"],
        cost: "Free",
        platforms: ["Web", "Android", "iOS", "Windows"],
        tags: ["vpn", "geo-restriction", "content access", "streaming", "native media"]
    },
    {
        id: "app-linguno",
        name: "Linguno",
        logoUrl: "../../images/logo_linguno.png",
        tagline: "Your ultimate adaptive conjugation and vocabulary coach.",
        myTake: "Most underrated app ever! Perfect for those who struggle to memorize conjugations! If you use it, you'll master them quickly. Why? Unlike Duolingo, this actually targets your weaknesses. So if you make a mistake, it will repeat until you get it right. It's frustrating at first, but that's how it is in the beginning. Once you rank high here, conjugating becomes very easy for you, almost without thinking. It's a key tool for drilling specific grammar points actively.",
        rating: 10,
        pros: ["User-friendly interface for targeted practice.", "Efficient adaptive learning system (like spaced repetition) that focuses on weaknesses.", "Excellent for mastering verb conjugations.", "Engaging vocabulary and listening exercises in sentence context.", "Free access to core features."],
        cons: ["Can be challenging for absolute new learners if they haven't seen the forms before.", "Limited number of languages compared to larger platforms.", "Interface might feel basic to some."],
        websiteUrl: "https://www.linguno.com/",
        androidUrl: null,
        iosUrl: null,
        windowsUrl: null,
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Low", A2: "High", B1: "Medium", B2: "Low", C1: "Low", C2: "Low" },
        immersionTypes: ["Grammar Focus", "Vocabulary Building", "Listening"],
        primaryCategories: ["Interactive Exercises", "Vocabulary Building"],
        skillFocus: ["Verb Conjugation Mastery", "Vocabulary Recall", "Grammar Accuracy"],
        cost: "Free",
        platforms: ["Web"],
        tags: ["conjugation practice", "verb drills", "vocabulary trainer", "adaptive learning", "grammar exercises"]
    },
    {
        id: "app-reversocontext",
        name: "Reverso Context",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Reverso_logo.jpg/1200px-Reverso_logo.jpg",
        tagline: "Your all-in-one toolkit for contextual translations and language resources.",
        myTake: "If you're studying a language, you probably need a grammar resource. For me, this is truly the best app. It's perfect for conjugation lists, vocabulary, synonyms, grammar checker, translator, or anything you can think of. Once you get the hang of it, you won't switch to another source because it's truly complete. The millions of example sentences are invaluable for understanding how words are used in real life. It's 9 stars because there are some paid features, but they aren't necessary or a hindrance to your learning. Everything you need is already free here.",
        rating: 9,
        pros: ["Comprehensive language learning resources in one place.", "Extensive translation database with words shown in real-life example sentences.", "Excellent verb conjugation and grammar tools.", "Synonyms, definitions, and learning games.", "Many core features are free."],
        cons: ["Some premium features (e.g., AI Rephraser, more examples, no ads) require a subscription.", "Interface can feel a bit cluttered at times with all the options.", "Offline use is limited or part of premium."],
        websiteUrl: "https://context.reverso.net/",
        androidUrl: "https://play.google.com/store/apps/details?id=com.reverso.context",
        iosUrl: "https://apps.apple.com/us/app/reverso-translate-and-learn/id919979642",
        windowsUrl: null,
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "High", A2: "High", B1: "Medium", B2: "Medium", C1: "Low", C2: "Low" },
        immersionTypes: ["Reading", "Writing", "Vocabulary Building", "Grammar Focus"],
        primaryCategories: ["Dictionary", "Translation Tool", "Grammar Focus"],
        skillFocus: ["Vocabulary in Context", "Understanding Idioms", "Grammar Reference", "Translation Nuance"],
        cost: "Freemium",
        platforms: ["Web", "Android", "iOS"],
        tags: ["contextual dictionary", "translation examples", "conjugation", "synonyms", "grammar checker"]
    },
    {
        id: "app-googletranslate",
        name: "Google Translate",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Google_Translate_logo.svg/1024px-Google_Translate_logo.svg.png",
        tagline: "Your versatile and widely accessible language companion.",
        myTake: "This is probably the most famous translator in the world. Its biggest advantage is that you can download language files to use it offline. That's good for people like me who don't buy mobile data. However, the translations here are very program-based and not human-based, so the translations aren't really great, especially for little nuances. I rarely use it because DeepL is much better. But if a language isn't on DeepL, I go straight to Google Translate.",
        rating: 8,
        pros: ["Supports a vast number of languages.", "Offline translation capabilities for many languages (requires downloading files).", "Image translation (via camera) and conversation mode are useful features.", "Completely free."],
        cons: ["Translation quality can be inconsistent and often lacks naturalness or nuance, especially for complex sentences.", "May struggle with idiomatic expressions or highly contextual text.", "Voice translation can be hit-or-miss."],
        websiteUrl: "https://translate.google.com/",
        androidUrl: "https://play.google.com/store/apps/details?id=com.google.android.apps.translate",
        iosUrl: "https://apps.apple.com/us/app/google-translate/id414706506",
        windowsUrl: null,
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "High", A2: "High", B1: "Medium", B2: "Medium", C1: "Low", C2: "Low" },
        immersionTypes: ["Reading", "Writing", "Vocabulary Building"],
        primaryCategories: ["Translation Tool", "Dictionary"],
        skillFocus: ["Quick Translation", "Vocabulary Lookup", "Gist Comprehension"],
        cost: "Free",
        platforms: ["Web", "Android", "iOS"],
        tags: ["translator", "dictionary", "offline translation", "multi-language"]
    },
    {
        id: "app-memrise",
        name: "Memrise",
        logoUrl: "https://upload.wikimedia.org/wikipedia/en/3/39/Memrise-new-logo.png",
        tagline: "Your vocabulary building companion with mnemonics.",
        myTake: "It's okay for learning vocabulary. The good thing here is it uses spaced-repetition, which is a good algorithm for maintaining vocabulary. And it's not as complicated as Duolingo. But there's a lot of inaccessible content, such as paid lessons, so that's also a downside. Good for initial exposure to words but less effective for deep, contextual understanding compared to Anki with self-made cards.",
        rating: 5,
        pros: ["Focus on vocabulary acquisition through spaced repetition and mnemonics.", "User-generated content provides a wide variety of courses and learning styles.", "Some courses incorporate native speaker audio and video clips ('Learn with Locals').", "Gamified approach can be engaging for some."],
        cons: ["Limited grammar and conversation practice in most courses.", "Relies heavily on memorization rather than deep comprehension or active use.", "Free version has significant limitations on content access and features, with frequent prompts to upgrade.", "Quality of user-generated courses can be inconsistent."],
        websiteUrl: "https://www.memrise.com/",
        androidUrl: "https://play.google.com/store/apps/details?id=com.memrise.android.memrisecompanion",
        iosUrl: "https://apps.apple.com/us/app/memrise-easy-language-learning/id635966718",
        windowsUrl: null,
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "High", A2: "Low", B1: "Very Low", B2: "Very Low", C1: "Very Low", C2: "Very Low" },
        immersionTypes: ["Vocabulary Building"],
        primaryCategories: ["Vocabulary Building", "SRS"],
        skillFocus: ["Vocabulary Memorization", "Mnemonic Learning"],
        cost: "Freemium",
        platforms: ["Web", "Android", "iOS"],
        tags: ["vocabulary", "flashcards", "spaced repetition", "mnemonics", "language learning app"]
    },
    {
        id: "app-duolingo",
        name: "Duolingo",
        logoUrl: "https://cdn.jim-nielsen.com/ios/512/duolingo-2019-01-02.png?rf=1024",
        tagline: "Your casual and gamified language introduction.",
        myTake: "It's okay for beginners and its game structure is good for initial exposure. But it has too many unnecessary things that aren't needed to learn a language effectively. And words you already know well, you still have to repeat instead of progressing to the next level. So it's slow for progress. It's like it's babying the learner. It also lacks real-world context, which is necessary for language learning. Use it very briefly for the first few lessons of a brand new language, then move on quickly to more robust methods.",
        rating: 4,
        pros: ["User-friendly and gamified interface, making it approachable for absolute beginners.", "Covers basic vocabulary and grammar fundamentals for many languages.", "Accessible across various devices.", "Motivating through streaks and leaderboards for some users."],
        cons: ["Very slow learning pace due to excessive repetition and rigid structure.", "Exercises can become repetitive with limited progress towards fluency.", "Lacks real-world language application and authentic contextual learning.", "Focuses heavily on translation rather than thinking in the target language.", "Aggressive monetization with hearts system and ads in free version; many features pushed to paid 'Super Duolingo'."],
        websiteUrl: "https://www.duolingo.com/", // Corrected from image URL in original HTML
        androidUrl: "https://play.google.com/store/apps/details?id=com.duolingo",
        iosUrl: "https://apps.apple.com/us/app/duolingo-language-lessons/id570060128",
        windowsUrl: null,
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "High", A2: "Low", B1: "Very Low", B2: "Very Low", C1: "Very Low", C2: "Very Low" },
        immersionTypes: ["Vocabulary Building", ],
        primaryCategories: ["Course Platform", "Interactive Exercises"],
        skillFocus: ["Basic Vocabulary", "Basic Grammar Introduction"],
        cost: "Freemium",
        platforms: ["Web", "Android", "iOS"],
        tags: ["beginner app", "gamified learning", "language basics", "vocabulary app"]
    },
    {
        id: "app-languagereactor",
        name: "Language Reactor",
        logoUrl: "https://lh3.googleusercontent.com/aPSUr3UYCdrkrGEIJu_5RubORwHcRiQEaiRKAPx68BeJ7963d31hIzZamn8HninChHNh-CIFWuRFj2cocG-2ojxl7oE=s120",
        tagline: "Your immersive companion for learning with videos.",
        myTake: "Speaking of YouTube, when you use subtitles, you often need to go to Google Translate to find the meaning of a word. With Language Reactor, you just hover your mouse over a word, and the translation appears. This saves a lot of time switching from one app to another. If you're a beginner, you can also see the translation of the whole phrase below to compare and contrast. But if you're a bit advanced, you can also blur it to make it more challenging. Then, if you don't understand the context, you can look at the translation. Aside from YouTube, it also works on Netflix and other streaming platforms, turning passive watching into active learning.",
        rating: 10,
        pros: ["Enhances video content (YouTube, Netflix) with interactive learning features.", "Offers dual-language subtitles for improved comprehension and comparison.", "Provides on-demand definitions and translations by hovering over words.", "Customizable learning experience (e.g., blur translations, auto-pause).", "Allows saving words and phrases for later review (integration with Anki possible via export)."],
        cons: ["Primarily a desktop browser extension; mobile experience is limited or non-existent.", "Full feature set often requires a subscription.", "Effectiveness relies heavily on the availability and quality of subtitles for the content.", "Might not be suitable for complete beginners who need more structured guidance before tackling native content, unless used with very simple material."],
        websiteUrl: "https://www.languagereactor.com/",
        androidUrl: null,
        iosUrl: null,
        windowsUrl: null,
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "High", A2: "Medium", B1: "Low", B2: "Very Low", C1: "Very Low", C2: "Very Low" },
        immersionTypes: ["Watching", "Listening", "Reading", "Vocabulary Building"],
        primaryCategories: ["Reading Assistant", "Utility", "Content Platform"],
        skillFocus: ["Auditory Comprehension with Visual Aid", "Vocabulary in Context", "Understanding Native Speech"],
        cost: "Freemium",
        platforms: ["Web"],
        tags: ["youtube learning", "netflix learning", "dual subtitles", "video immersion", "interactive subtitles"]
    },
    {
        id: "app-clozemaster",
        name: "ClozeMaster",
        logoUrl: "https://play-lh.googleusercontent.com/OnFqiujFXmyzOvkmaCzPDPHPnN9-mcM9hBwQPLAXy3lESDbkHqXQTRRzfJvchwDkNds=w240-h480-rw",
        tagline: "Your Contextual Vocabulary Builder through Gap-Fill.",
        myTake: "This used to be one of my favorite apps. This is where I first truly exposed myself to context because you fill in the blanks for the word that fits the sentence. So you really need to have an idea of what the words mean. It has two modes: multiple choice or you type the word yourself. When you're a bit more advanced, just use the typing mode. It's incredibly good. But I stopped using it when they imposed a limit of 30 exercises a day and then required payment. That's why it's only 6 stars now. It used to be a solid 10 stars for me; I used it all the time.",
        rating: 6,
        pros: ["Excellent for learning vocabulary through contextual sentences (cloze deletion).", "Fill-in-the-blanks exercises reinforce understanding and usage.", "Offers multiple choice and typing modes for varied difficulty.", "Exposure to a massive number of sentences, often sourced from Tatoeba.", "Gamified elements and leaderboards."],
        cons: ["Free version is severely limited (e.g., 30 sentences per language per day).", "Requires a Pro subscription for unlimited access and all features.", "Sentence quality can sometimes be variable or unnatural.", "Might be less engaging for those who prefer other learning styles over repetitive drills."],
        websiteUrl: "https://www.clozemaster.com/",
        androidUrl: "https://play.google.com/store/apps/details?id=com.clozemaster.ClozeMaster",
        iosUrl: "https://apps.apple.com/us/app/clozemaster/id1109098371",
        windowsUrl: null,
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Low", A2: "High", B1: "Medium", B2: "Very Low", C1: "Very Low", C2: "Very Low" }, // Adjusted, rating was 6, suitability was High for B1 but "Very Low" for B2 in table
        immersionTypes: ["Reading", "Vocabulary Building", "Grammar Focus"],
        primaryCategories: ["Interactive Exercises", "Vocabulary Building"],
        skillFocus: ["Vocabulary in Context", "Sentence Structure Recognition", "Active Recall"],
        cost: "Freemium", // Heavily leans to paid for full use
        platforms: ["Web", "Android", "iOS"],
        tags: ["cloze deletion", "vocabulary in context", "fill in the blanks", "sentence mining"]
    },
    {
        id: "app-italki",
        name: "iTalki",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c5/Italki-logo-2023.png",
        tagline: "Find your perfect language tutor for personalized lessons.",
        myTake: "For me, iTalki is truly the best for finding real teachers trained to teach languages. From beginner to advanced, you will be guided. The methods vary based on your level. The only catch is you have to pay. But it's relatively cheap (e.g., ~250 pesos per 30 minutes, varies by tutor). And the great thing is, it's anytime you want! Just book a schedule that fits you. Your payment is really worth it here, especially if you find the perfect teacher. The only hard part is that the quality of your learning really depends on the teacher, so it's trial and error. It's also available in most languages you can think of. (Promo Code: ALJOHN for $5 free on first $10 purchase - *note this may be outdated*).",
        rating: 10,
        pros: ["One-on-one tutoring with qualified language experts and community tutors.", "Real-time feedback and personalized instruction.", "Flexible scheduling to fit your lifestyle.", "Access to native speakers from around the world for authentic practice.", "Wide range of languages offered."],
        cons: ["Requires financial investment for lessons; cost can add up.", "Tutor quality and teaching style can vary significantly; finding the right fit may take trial and error.", "Reliant on internet connection for lessons."],
        websiteUrl: "https://go.italki.com/aljohnpolyglot", // Your promo link
        androidUrl: "https://italki.app.link/aljohnpolyglot", // Your app link
        iosUrl: "https://italki.app.link/aljohnpolyglot", // Assuming same app link works
        windowsUrl: null, // Web-based
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Low", A2: "Low", B1: "Medium", B2: "High", C1: "High", C2: "High" },
        immersionTypes: ["Speaking", "Listening", "Writing", "Grammar Focus"], // Depending on lesson type
        primaryCategories: ["Language Exchange", "Course Platform"], // Tutoring platform
        skillFocus: ["Conversational Fluency", "Pronunciation Correction", "Grammar Accuracy", "Personalized Learning"],
        cost: "Paid", // Pay per lesson
        platforms: ["Web", "Android", "iOS"],
        tags: ["tutoring", "language lessons", "native speakers", "speaking practice", "personalized learning"]
    },
    {
        id: "app-tandem",
        name: "Tandem",
        logoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJ-w0GNMvwhnXn9oHi0j8RKlt_vq6-DMeGqw&s",
        tagline: "Your global language exchange partner community.",
        myTake: "For me, this is also where my speaking skills were really honed. Unlike Discord's server limits sometimes, Tandem connects you directly with individuals. You can also create your own 'parties' (group voice calls) if others are full. That's what's great about it because you can jump straight into conversations. Most of the people I became close to here, I met in parties through voice calls. That's its difference from HelloTalk, where you often have to approach through chat, which can be a bit awkward. Great for real-world practice.",
        rating: 9, // Your text says 10, but table says 9. Going with table.
        pros: ["Connects language learners with native speakers worldwide for mutual exchange.", "Offers text, voice, and video chat options.", "Provides opportunities for real-world language practice and cultural exchange.", "Encourages mutual language learning and teaching.", "'Parties' feature for group calls is a good way to jump into speaking."],
        cons: ["Language exchange quality can vary greatly based on the partner's commitment and teaching ability.", "Limited availability of active partners for less common languages or specific time zones.", "Like any social platform, interactions can sometimes be inconsistent or off-topic."],
        websiteUrl: "https://www.tandem.net/",
        androidUrl: "https://play.google.com/store/apps/details?id=net.tandem",
        iosUrl: "https://apps.apple.com/us/app/tandem-language-exchange/id959001619",
        windowsUrl: null, // Web-based for some features
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Very Low", A2: "Very Low", B1: "Medium", B2: "High", C1: "High", C2: "High" },
        immersionTypes: ["Speaking", "Listening", "Writing"], // Writing via chat
        primaryCategories: ["Language Exchange"],
        skillFocus: ["Conversational Practice", "Cultural Exchange", "Building Fluency"],
        cost: "Freemium", // Core is free, Pro version for unlimited translations, no ads, etc.
        platforms: ["Web", "Android", "iOS"],
        tags: ["language exchange", "native speakers", "conversation practice", "cultural immersion", "chat app"]
    },
    {
        id: "app-languagesloth", // Assuming this is the Discord server
        name: "Language Sloth Discord Server",
        logoUrl: "https://styles.redditmedia.com/t5_5gtap7/styles/communityIcon_mx50us3tmet91.png", // Official Discord logo might be better: https://cdn.logo.com/hotlink-ok/logo-social.png
        tagline: "Your vibrant language learning community on Discord.",
        myTake: "This is truly my happy place when I practice languages. You just need to know what timezone your target language is active in. And people are very friendly. Just enter the voice room for the language you want to practice, and then, just talk. I spent hundreds of hours on this server, and this is where I really honed my speaking skills. But it's 9 stars because sometimes the server is full, or specific language rooms might be quiet or you might feel out of place (OP) because you're new.",
        rating: 9,
        pros: ["Immersive language practice with native speakers and fellow learners in real-time.", "Variety of language-specific channels and interest groups.", "Opportunities for cultural exchange and making friends.", "Generally free to join and participate.", "Active community for many major languages."],
        cons: ["Relies heavily on active member participation; some language rooms can be quiet at times.", "Finding consistent partners can be inconsistent due to time zones and availability.", "Quality of interactions can vary; not a formal tutoring environment.", "Can be overwhelming for newcomers to navigate large servers."],
        websiteUrl: "https://discord.com/invite/languages", // General Discord invite, or specific server if available
        androidUrl: "https://play.google.com/store/apps/details?id=com.discord",
        iosUrl: "https://apps.apple.com/us/app/discord-chat-talk-hangout/id985746746",
        windowsUrl: "https://discord.com/download",
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Very Low", A2: "Very Low", B1: "Medium", B2: "High", C1: "High", C2: "High" },
        immersionTypes: ["Speaking", "Listening", "Writing"], // Writing via text channels
        primaryCategories: ["Language Exchange", "Community"],
        skillFocus: ["Real-time Conversation Practice", "Informal Speaking", "Listening to Various Accents"],
        cost: "Free",
        platforms: ["Web", "Android", "iOS", "Windows"],
        tags: ["discord server", "language community", "speaking practice", "voice chat", "language exchange"]
    },
    {
        id: "app-gliglish",
        name: "Gliglish",
        logoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_EG7va_DHNEdjYthmQY520wIEiWO1fdqAeg&s", // Consider official logo if available
        tagline: "Your AI conversation partner for practicing real-world scenarios.",
        myTake: "This is good if you don't have money for a teacher to practice your language. You can practice in various situations here, like in a cafe, school, library, etc. It also has a voice feature you can use with your mic if you're lazy to type. The best part is, it's really for language learners, and the virtual teacher will correct your grammar mistakes. However, we need to remember this is just AI, and it's still different if a real person is teaching you. But I really recommend using this before you try to speak with real native speakers for initial confidence building.",
        rating: 8,
        pros: ["Immersive conversational learning experience with AI in various scenarios.", "Provides real-time feedback on grammar and pronunciation (for some languages).", "Offers a variety of conversation topics and role-play situations.", "Convenient and accessible for practice anytime.", "Voice input for hands-free practice."],
        cons: ["Potential for technical glitches or AI misunderstandings.", "May not fully capture all nuances of human conversation or culture.", "Subscription-based for full access to all features and languages.", "AI feedback might not always be perfectly accurate or contextual."],
        websiteUrl: "https://gliglish.com/",
        androidUrl: null, // Primarily web-based
        iosUrl: null,
        windowsUrl: null,
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Very Low", A2: "Very Low", B1: "High", B2: "Medium", C1: "Medium", C2: "Medium" },
        immersionTypes: ["Speaking", "Listening"],
        primaryCategories: ["AI Tutor", "Language Exchange"],
        skillFocus: ["Scenario-based Conversation", "Pronunciation Practice", "Grammar Correction (AI)"],
        cost: "Freemium", // Limited free trial, then subscription
        platforms: ["Web"],
        tags: ["ai conversation", "speaking practice", "role playing", "ai tutor", "grammar feedback"]
    },
    {
        id: "app-polyai", // SpeakMaster
        name: "PolyAI (SpeakMaster AI)",
        logoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNgr2cyzDsrVIPn_-ul9FzrWecnzNXfK8s0w&s",
        tagline: "Your AI conversation partner with diverse characters.",
        myTake: "If you want to practice your language skills, this is okay! You can chat with your favorite characters, from cartoons like Spongebob to your favorite movie characters or even celebrities. This app is available in major Romance and Asian languages. There's even Tagalog! Your conversational skills will surely be honed here. But I only give it 7 stars because you're just talking to AI, and human interaction is still better. Also, this app isn't really for language learning, so it won't correct your mistakes. More for fun, lower-pressure practice.",
        rating: 7,
        pros: ["Engaging conversational AI with a diverse range of characters (celebrities, fictional).", "Potential for immersive and entertaining language practice.", "Offers a variety of conversation topics based on character personas.", "Can be less intimidating than talking to real people for some."],
        cons: ["Primarily focused on entertainment rather than structured language learning.", "Limited language options and customization for learning purposes.", "Does not provide structured lessons, grammar corrections, or feedback.", "AI responses can be generic or repetitive."],
        websiteUrl: null, // Primarily app based
        androidUrl: "https://play.google.com/store/apps/details?id=ai.socialapps.speakmaster&hl=en",
        iosUrl: null, // Check App Store
        windowsUrl: null,
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Very Low", A2: "Very Low", B1: "Medium", B2: "High", C1: "High", C2: "High" }, // For very casual practice
        immersionTypes: ["Speaking", "Listening"],
        primaryCategories: ["AI Tutor", "Language Exchange"], // Loosely
        skillFocus: ["Casual Conversation Practice", "Maintaining Fluency (Low Stakes)"],
        cost: "Freemium", // Often has free chats with ads, or coin system
        platforms: ["Android"], // iOS to be checked
        tags: ["ai chat", "character ai", "fun practice", "casual conversation"]
    },
    {
        id: "app-hellotalk",
        name: "HelloTalk",
        logoUrl: "https://play-lh.googleusercontent.com/_n5qVwKyfl5QiJjyZiTvTM8z4WN63Da8EAhRUkKtLMjIZ3aHNkAXlvF89V_uzYMQxg",
        tagline: "Your social language practice and exchange platform.",
        myTake: "This is good for those looking for language partners. It's really like social media disguised as a language app where you can see their posts ('Moments') and message them. This app is really okay, but there are too many flirty people, so it's only 6 stars. It can be harder to jump straight into voice calls compared to Tandem's 'parties' as it often starts with text chat, which can feel awkward if you primarily want speaking practice. Still a decent option if you're patient.",
        rating: 6,
        pros: ["Connects language learners with native speakers for language exchange.", "Offers various communication tools (text, voice messages, voice/video calls).", "Features like 'Moments' (social posts) allow for cultural exchange and finding partners.", "Built-in translation and correction tools can be helpful."],
        cons: ["Focus has sometimes shifted from serious language learning to social networking or dating for some users.", "Increased prevalence of inappropriate content or spam messages from some users.", "Finding genuine, committed language exchange partners can be challenging.", "Free version has limitations (e.g., on translations, number of partners)."],
        websiteUrl: "https://www.hellotalk.com/?lang=en",
        androidUrl: "https://play.google.com/store/apps/details?id=com.hellotalk",
        iosUrl: "https://apps.apple.com/us/app/hellotalk-language-learning/id557130558",
        windowsUrl: null, // Web version available
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Very Low", A2: "Very Low", B1: "Medium", B2: "High", C1: "High", C2: "High" },
        immersionTypes: ["Speaking", "Listening", "Writing"],
        primaryCategories: ["Language Exchange", "Community"],
        skillFocus: ["Conversation Practice", "Text Chat", "Cultural Exchange"],
        cost: "Freemium",
        platforms: ["Web", "Android", "iOS"],
        tags: ["language exchange", "chat app", "native speakers", "social learning"]
    },
    {
        id: "app-radiogarden",
        name: "Radio Garden",
        logoUrl: "https://play-lh.googleusercontent.com/07lewhVI4GklVBi_ehhOXxmB_bPaWWTiyqHAlQP6VsYD7h9R4d8hskNAy4SCOx0leNx-",
        tagline: "Your interactive global radio tuner for live immersion.",
        myTake: "If you want to practice listening, you can access almost all radio stations in the world here by spinning a globe. All you need is Wi-Fi, and you're good to go. But the hard part is finding a radio station that's consistently in your target language and engaging. Often, you can't fully immerse because some stations also play American music or have lots of ads. So, that can also slow down your progress instead of listening to your full target language. It's great for passive background exposure to the sounds and rhythm, though.",
        rating: 8,
        pros: ["Vast collection of live radio stations from around the world.", "Interactive map interface for exploring stations by location.", "Exposure to authentic accents, music, and talk shows in the target language.", "Free to use."],
        cons: ["Limited control over specific content; depends on what's live.", "Content availability and quality varies greatly by station and region.", "Potential for audio quality issues or buffering.", "Many stations play international (e.g., English) music, diluting target language immersion.", "Can be hard to find stations that are 100% talk in target language without extensive searching."],
        websiteUrl: "https://radio.garden/",
        androidUrl: "https://play.google.com/store/apps/details?id=com.jonathanpuckey.radiogarden",
        iosUrl: "https://apps.apple.com/us/app/radio-garden-live/id1336237040",
        windowsUrl: null, // Web-based
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Very Low", A2: "Medium", B1: "High", B2: "High", C1: "High", C2: "High" }, // Note: Table had two Radio Garden entries with same ratings.
        immersionTypes: ["Listening"],
        primaryCategories: ["Media Player", "Content Platform"],
        skillFocus: ["Passive Listening", "Exposure to Natural Speech Flow", "Cultural Immersion (Music/Talk)"],
        cost: "Free",
        platforms: ["Web", "Android", "iOS"],
        tags: ["live radio", "global radio", "listening immersion", "passive listening", "world music"]
    },
    // Apps from your new list, with "My Take" synthesized from your descriptions and overall philosophy
    {
        id: "immersivetranslate",
        name: "Immersive Translate (Browser Extension/Tool)",
        logoUrl: "https://play-lh.googleusercontent.com/2fO3QcwZqGMEO5LKBbzzqaTPJQrZ1bMMT4blE3LWMLdmuUfAbTUzf60rCZi9l3twzDt7=w240-h480-rw", // User provided
        tagline: "Read ANY Book or Webpage in Your Target Language, Instantly.",
        myTake: "This is an absolute GOLDMINE, a 10-star tool for me, especially when I can't find a book directly in my target language. I just find an English EPUB or website, run it through Immersive Translate, and I can read it in my target language with dual-language views or click-to-translate. It has massively expanded the sheer volume of reading material available to me, ensuring I'm never choosy about content and can always be immersed. This is crucial from A2 (if your English is good enough to understand the source) all the way to C2. No more wasted time searching for perfectly graded readers; this tool helps make *any* content comprehensible. It was part of my strategy for writing academic papers in my target language and then translating them.",
        rating: 10,
        pros: ["Translates entire ebooks (EPUB, PDF) and web pages in-browser.", "Offers dual-language or target-language-only views.", "Click-to-translate individual words or phrases for quick understanding.", "Vastly expands accessible reading material for any language it supports.", "Can aid in understanding complex texts by providing quick translations.", "Supports many languages."],
        cons: ["Translation quality is still machine-based, so not always perfect; nuances can be lost.", "Most effective if you have a decent understanding of the source language (often English).", "Browser extension performance can vary; some features might be premium.", "Requires online connectivity for translation."],
        websiteUrl: "https://immersive-translate.com/", // General website for the tool/extensions
        androidUrl: null, // Primarily desktop browser extensions
        iosUrl: null,
        windowsUrl: null, // Via browser extensions
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Very Low", A2: "Medium", B1: "High", B2: "High", C1: "High", C2: "High" }, // Requires some base in source language for A2
        immersionTypes: ["Reading", "Vocabulary Building"],
        primaryCategories: ["Translation Tool", "Reading Assistant", "Utility"],
        skillFocus: ["Reading Comprehension of Native Texts", "Vocabulary Acquisition in Context", "Making Difficult Content Accessible"],
        cost: "Freemium", // Core features often free, advanced features or higher usage may be paid
        platforms: ["Web"], // Browser extensions
        tags: ["ebook translation", "webpage translation", "bilingual reading", "assisted reading", "content access", "must-have"]
    },
    {
        id: "webtoon",
        name: "WEBTOON",
        logoUrl: "https://cdn.worldvectorlogo.com/logos/webtoon-logo.svg", // User provided
        tagline: "Engaging Digital Comics for Immersive Reading in Many Languages.",
        myTake: "This is pure gold, a 10-star resource for me, usable from A1 all the way to C2 depending on the story and your approach. The visual context from the comics makes understanding so much easier, especially for beginners. There's a vast library with unique stories in many languages, so you're learning with content you genuinely enjoy. The only 'downside' is you can't copy-paste text easily, so you have to manually type unknown words into a translator – but honestly, that can actually reinforce your learning! It was one of my core tools from the very beginning.",
        rating: 10,
        pros: ["Vast library of digital comics (webtoons) available in numerous languages.", "Strong visual context greatly aids reading comprehension, especially for beginners.", "Engaging stories across diverse genres keep learning enjoyable.", "Many webtoons are free to read.", "Multi-platform access (web and mobile apps).", "Exposure to natural, often colloquial, dialogue."],
        cons: ["Inability to easily copy text can slow down vocabulary lookup (though manual lookup can aid memory).", "Some popular series use a 'Fast Pass' system (pay to read ahead).", "Quality of translations for official versions in some languages might vary; fan translations are unofficial.", "App navigation can sometimes be overwhelming with the amount of content."],
        websiteUrl: "https://www.webtoons.com/en/",
        androidUrl: "https://play.google.com/store/apps/details?id=com.naver.linewebtoon",
        iosUrl: "https://apps.apple.com/us/app/webtoon-comics/id894424282",
        windowsUrl: null, // Access via website
        fullResourcePageUrl: null,
        cefrSuitability: { A1: "Medium", A2: "High", B1: "High", B2: "High", C1: "High", C2: "High" }, // A1 with careful selection
        immersionTypes: ["Reading", "Watching", "Vocabulary Building"], // "Watching" due to visual storytelling
        primaryCategories: ["Content Platform", "Reading Assistant"],
        skillFocus: ["Reading Comprehension with Visual Context", "Vocabulary Acquisition", "Exposure to Colloquial Language", "Cultural Insights"],
        cost: "Freemium", // Largely free, with optional paid features
        platforms: ["Web", "Android", "iOS"],
        tags: ["comics", "digital comics", "webcomics", "visual learning", "reading practice", "storytelling", "must-have"]
    }
];